apiVersion: v1
kind: Service
metadata:
  name: medvision-api
  namespace: medvision
spec:
  selector:
    app: medvision-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
