apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medvision-ingress
  namespace: medvision
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "32m"
spec:
  ingressClassName: nginx
  rules:
    - host: api.medvision.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: medvision-api
                port:
                  number: 8000
    - host: app.medvision.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: medvision-streamlit
                port:
                  number: 8501
