apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: medvision
resources:
  - namespace.yaml
  - configmap.yaml
  - api-deployment.yaml
  - api-service.yaml
  - streamlit-deployment.yaml
  - streamlit-service.yaml
  # Uncomment if ingress controller is installed:
  # - ingress.yaml
